export const layoutlg = [
    { i: '1', x: 0, y: 0, w: 6, h: 4, static: true },
    { i: '2', x: 6, y: 0, w: 3, h: 2, static: true },
    { i: '3', x: 9, y: 0, w: 3, h: 2, static: true },
    { i: '4', x: 6, y: 2, w: 3, h: 2, static: true },
    { i: '5', x: 9, y: 2, w: 3, h: 2, static: true },
    { i: '6', x: 0, y: 4, w: 3, h: 2, static: true },
    { i: '7', x: 3, y: 4, w: 3, h: 2, static: true },
    { i: '8', x: 6, y: 4, w: 3, h: 2, static: true },
    { i: '9', x: 9, y: 4, w: 3, h: 2, static: true },
    { i: '10', x: 0, y: 6, w: 3, h: 2, static: true },
    { i: '11', x: 3, y: 6, w: 3, h: 2, static: true },
    { i: '12', x: 6, y: 6, w: 3, h: 2, static: true },
    { i: '13', x: 9, y: 6, w: 3, h: 2, static: true },
  ]